spring.application.name=TrabalhoFaculLP1-e-A
spring.datasource.url=jdbc:mysql://localhost:3306/evt
spring.datasource.username=root
spring.datasource.password=Hnrqbassilind123!
server.port=8081

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

secret.key=henriquelindmanbassi 

